import Contact from "@/component/Contact";
import { Inter } from "@next/font/google";
import Head from "next/head";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const inner_html = () => <img src={`/Images/banner.png`} />;
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" w-screen h-screen  flex-1 flex  flex-col overflow-auto bg-no-repeat overflow-x-hidden  snap-y snap-mandatory">
        <section
          id="home"
          className="snap-start justifiy-between items-center bg-no-repeat "
          style={{
            backgroundImage: `url(/Images/banner.png)`,
          }}>
          <div className="container mx-auto flex flex-row justify-between items-center">
            <div className="text-white text-7xl w-screen">
              <i>Where being the pet is just best!</i>
            </div>
            <div className="w-[12px]"></div>
            <div className=" z-10 h-fit w-fit bottom-1 mt-[11rem]">
              <img src={`/Images/Dog.png`} className="w-[800rem] h-[50rem] " />
            </div>
          </div>
        </section>

        <section className="snap-start ">
          <div className="container mx-auto py-32 text-[#3c6e71] space-y-10">
            <div className=" text-4xl text-center ">
              <h1>
                <b> Services </b>For <br />
                Your <b>Pets</b>
              </h1>
              <h4>
                {" "}
                <i>We care the way you care</i>
              </h4>
            </div>
            <div className="w-full  flex  justify-between items-center">
              <Link href="/grooming">
                <div className="m-4 flex flex-col justify-between items-center gap-5 ">
                  <span className="font-bond text-black text-2xl flex justify-between ">
                    GROOMING
                  </span>
                  <img
                    src="Images/grooming.jpg"
                    className="w-[20rem] h-[15rem] rounded-full shadow-2xl hover:scale-125 transition-all"
                  />
                </div>
              </Link>

              <Link href="/daycare">
                <div className="m-4 flex flex-col justify-between items-center gap-5">
                  <span className="font-bond text-black text-2xl flex justify-between ">
                    DAYCARE
                  </span>
                  <img
                    src="Images/daycare.jpeg"
                    className="w-[20rem] h-[15rem] rounded-full shadow-2xl  hover:scale-125 transition-all "
                  />
                </div>
              </Link>
              <Link href="/training">
                <div className="m-4 flex flex-col justify-between items-center gap-5 ">
                  <span className="font-bond text-black text-2xl flex justify-between ">
                    TRAINING
                  </span>
                  <img
                    src="Images/training.webp"
                    className="w-[20rem] h-[15rem] rounded-full shadow-2xl hover:scale-125 transition-all"
                  />
                </div>
              </Link>
            </div>
          </div>
          {/* <div className="bg-white-500 w-screen h-screen container mx-auto">
            <div className="text-red-500 text-6xl w-screen font-serif-Times_New_Roman text-left">
              <h1 className="">
                <b> Services </b>For <br />
                Your <b>Pets</b>
                <h4>
                  {" "}
                  <i>We care the way you care</i>
                </h4>
              </h1>
              <div className="text-gray-500 text-3xl  font-sans-ui-sans-serif text-left px-10 py-10">
                <div className="flex justify-between container mx-auto w-screen overflow-x-auto ">
                  <div className="m-4 flex flex-col justify-between items-center gap-5">
                    <span className="font-bond text-black text-2xl flex justify-between ">
                      GROOMING
                    </span>
                    <img
                      src="Images/grooming.jpg"
                      className="w-[20rem] h-[15rem] rounded-full shadow-2xl "
                    />
                  </div>
                  <div className="m-4 flex flex-col justify-between items-center gap-5">
                    <span className="font-bond text-black text-2xl flex justify-between ">
                      DAYCARE
                    </span>
                    <img
                      src="Images/daycare.jpeg"
                      className="w-[20rem] h-[15rem] rounded-full shadow-2xl "
                    />
                  </div>
                  <div className="m-4 flex flex-col justify-between items-center gap-5">
                    <span className="font-bond text-black text-2xl flex justify-between ">
                      TRAINING
                    </span>
                    <img
                      src="Images/training.webp"
                      className="w-[20rem] h-[15rem] rounded-full shadow-2xl "
                    />
                  </div>
                  
                </div>
              </div>
            </div>
          </div> */}
        </section>

        <section className="snap-start">
          {/* <div className="bg-white-500 w-screen h-screen">
            <div className="w-[30rem] h-[15rem] px-10 py-20">
              <img src="Images/cat dog.jpg" />
            </div>

            <div className="text-black-500 text-7xl w-screen font-serif-Times New Roman text-center">
              <h1>
                <br />
                <b>About us</b>
              </h1>
              <div className="text-gray-500 text-3xl w-screen font-serif text-center ">
                <h4>
                  {" "}
                  <i>
                    WAGGYis a unique marketplace <br />
                    where you can find one of a kind products <br />
                    to pamper your furry, finned, or feathered pet friend.
                  </i>
                </h4>
              </div>
            </div>
          </div> */}
        </section>
        <section className="bg-white dark:bg-gray-900 snap-start">
          <Contact />
        </section>

        {/* <section className="snap-start">
          <div className="bg-white-500 w-screen h-screen">
            <div className="text-black-500 text-5xl w-screen font-serif text-left px-10 py-20">
              <h1>
                <br />
                <b>Contact Us</b>
              </h1>
            </div>

            <form className="w-full max-w-sm px-10 py-0 ">
              <div className="md:flex md:items-center mb-6">
                <div className="md:w-1/3">
                  <label
                    className="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4"
                    htmlFor="inline-full-name">
                    <h4>Full Name</h4>
                  </label>
                </div>
                <div className="md:w-2/3">
                  <input
                    className="bg-gray-300 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500"
                    id="inline-full-name"
                    type="text"
                  />
                </div>
              </div>
              <div className="md:flex md:items-center mb-6">
                <div className="md:w-1/3">
                  <label
                    className="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4"
                    htmlFor="inline-password">
                    <h4>Email</h4>
                  </label>
                </div>
                <div className="md:w-2/3">
                  <input
                    className="bg-gray-300 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500"
                    id="inline-password"
                    type="password"
                  />
                </div>
              </div>
              <div className="md:flex md:items-center mb-6">
                <div className="md:w-1/3">
                  <label
                    className="block text-gray-500 font-bold md:text-right mb-1 md:mb-0 pr-4"
                    htmlFor="inline-full-name">
                    <h4>Message</h4>
                  </label>
                </div>
                <div className="md:w-2/3">
                  <input
                    className="bg-gray-300 appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-purple-500"
                    id="inline-full-name"
                    type="text"
                  />
                </div>
              </div>

              <div className="md:flex md:items-center">
                <div className="md:w-1/3"></div>
                <div className="md:w-2/3">
                  <button
                    className="shadow bg-purple-500 hover:bg-purple-400 focus:shadow-outline focus:outline-none text-white font-bold py-2 px-4 rounded"
                    type="button">
                    Send Message
                  </button>
                </div>
              </div>
            </form>
            <img src="Images/contact.jpg" className="w-[20rem] h-[15rem] r shadow-2xl   " />
          </div>
        </section> */}
      </div>
    </>
  );
}

Home.auth = false;
