import { Inter } from "@next/font/google";
import { getSession } from "next-auth/react";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  (async () => {
    const session = await getSession();
    console.log(session);
  })();

  const inner_html = () => <img src={`/Images/banner.png`} />;
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" w-screen h-screen  flex-1 flex  flex-col overflow-auto bg-no-repeat  snap-y snap-mandatory">
        <section
          id="home"
          className="snap-start justifiy-between items-center bg-no-repeat "
          style={{
            backgroundImage: `url(/Images/banner.png)`,
          }}>
          <div className="container mx-auto flex flex-row justify-between items-center">
            <div className="text-white text-7xl w-screen">
              <i>Where being the pet is just best!</i>
            </div>
            <div className="w-[12px]"></div>
            <div className=" z-10 h-fit w-fit bottom-1 mt-[11rem]">
              <img src={`/Images/Dog.png`} className="w-[800rem] h-[50rem] " />
            </div>
          </div>
        </section>
        <section className="snap-start">
          <div className="bg-yellow-500 w-screen h-screen">1</div>
        </section>
        <section className="snap-start">
          <div className="bg-green-500 w-screen h-screen">2</div>
        </section>
        <section className="snap-start">
          <div className="bg-blue-500 w-screen h-screen">3</div>
        </section>
      </div>
    </>
  );
}

Home.auth = false;
